name: ci/cd
on:
  push:
    branches:
      - master
    tags:
      - '!*' # Do not execute on tags
  pull_request:

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.31.0
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: setup and test
        run: |
          pnpm install
          pnpm lint
          pnpm build

      - name: upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
          retention-days: 7

  jest:
    name: jest tests coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.31.0
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: setup and test
        run: |
          pnpm install --no-optional
          pnpm jest -- --coverage

      - name: upload jest artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: jest
          path: results/jest
          retention-days: 7

  cypress:
    name: cypress e2e tests coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.31.0
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: setup and test
        run: |
          pnpm install
          pnpm e2e

      - name: upload cypress artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cypress
          path: results/cypress
          retention-days: 7

  deploy:
    name: coverage combined report
    runs-on: ubuntu-latest
    needs: [build, jest, cypress]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: install pnpm
        run: curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm

      - name: download dist artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: download jest artifacts
        uses: actions/download-artifact@v2
        with:
          name: jest
          path: results/jest

      - name: download cypress artifacts
        uses: actions/download-artifact@v2
        with:
          name: cypress
          path: results/cypress

      - name: merge artifacts
        run: |
          npm install -g nyc
          node nyc-report

      - uses: paambaati/codeclimate-action@84cea27117a473d605400ca3a97fcef7e433e2d6
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: dist/coverage/lcov.info:lcov

      - uses: JamesIves/github-pages-deploy-action@4a4e918eebde22924fa8cca4d1b94cbcc85a810e
        with:
          branch: pages
          folder: dist
        if: github.ref == 'refs/heads/master'
