name: ci/cd
on:
  push:
    branches:
      - master
    tags:
      - '!*' # Do not execute on tags
  pull_request:

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: setup and test
        run: |
          pnpm install --no-optional
          pnpm lint
          pnpm build

      - name: upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
          retention-days: 7

  jest:
    name: jest tests coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: setup and test
        run: |
          pnpm install --no-optional
          pnpm jest --coverage

      - name: upload jest artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jest
          path: results/jest
          retention-days: 7

  cypress:
    name: cypress e2e tests coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
      - uses: actions/cache@v3
        with:
          path: /home/runner/.cache/Cypress

      - name: setup and test
        run: |
          pnpm install
          pnpm cypress install
          pnpm e2e

      - name: upload cypress artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress
          path: results/cypress
          retention-days: 7

  deploy:
    name: coverage combined report
    runs-on: ubuntu-latest
    needs: [build, jest, cypress]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: download dist artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: download jest artifacts
        uses: actions/download-artifact@v3
        with:
          name: jest
          path: results/jest

      - name: download cypress artifacts
        uses: actions/download-artifact@v3
        with:
          name: cypress
          path: results/cypress

      - name: Code Climate Coverage Action
        uses: paambaati/codeclimate-action@v4.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            results/cypress/lcov.info:lcov
            results/jest/lcov.info:lcov

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.2
        with:
          branch: pages
          folder: dist
        if: github.ref == 'refs/heads/master'
