name: code climate
on:
  push:
    branches:
      - master
    tags:
      - '!*' # Do not execute on tags
    paths:
      - src/*
  pull_request:
    paths:
      - src/*

jobs:
  test:
    name: unit tests coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
    - uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c
      with:
        node-version: 16
    - run: yarn install
    - uses: paambaati/codeclimate-action@84cea27117a473d605400ca3a97fcef7e433e2d6
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: yarn coverage
